/*
 * nurgazinov.com — portfolio front-end (vanilla JS, no build step)
 *
 * Sections handled here:
 *   1. Loader          – real progress (fonts, three.js, first 3D frame, showreel buffer, posters)
 *   2. 3D cinema hero  – three.js hall, velvet curtains, audience silhouettes, projector beam
 *   3. Hero UI         – custom "CLICK" cursor, letter-warp title, curtain toggle
 *   4. Nav             – hand-drawn scribble underline, new shape on every hover
 *   5. About           – scroll-linked blur fly-in + 0→10 counter
 *   6. AI films        – accordion rows with inline video players
 *   7. Lazy loops      – [data-autoplay] videos play only while on screen (work tiles, project pages)
 *
 * three.js r159 (UMD build, window.THREE) is loaded async from assets/js/three.min.js.
 */
(function () {
  'use strict';

  const $ = (sel, root) => (root || document).querySelector(sel);
  const $$ = (sel, root) => Array.prototype.slice.call((root || document).querySelectorAll(sel));
  const ref = (name) => $('[data-ref="' + name + '"]');
  const prefersReduced = () => window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  // Film rows are generated by scripts/build.mjs from content/films.json.
  // Each <li class="film"> carries data-secs; the real duration replaces it once metadata loads.

  class Site {
    constructor() {
      this.state = { curtainOpen: false, no3d: false, openFilm: 0, playing: false, ft: 0 };
      this.vid = ref('video');
      if (this.vid) this.vid.muted = true;
      this.cv = ref('canvas');
      this.bcv = ref('beam');
      this.hc = ref('cursor');
      this.logoEl = ref('logo');
      this.aboutEl = ref('about');
      this.countEl = ref('count');
      this.titleEl = ref('title');
      this.titleLetters = null;
      this.stage = $('.stage3d');
      this.curtainsBtn = ref('curtains');
      this.fvs = $$('[data-ref="filmVideo"]');
      this.mouse = { x: 0, y: 0, tx: 0, ty: 0 };
      this.hover = false;
      this.hv = 0;
      this.target = 0;
      this.p = 0;
      this.visible = true;
    }

    setState(patch) {
      Object.assign(this.state, patch);
      this.renderHero();
      this.renderFilms();
    }

    // ---------------------------------------------------------------- hero
    renderHero() {
      const s = this.state;
      if (this.stage) {
        this.stage.classList.toggle('open', !!s.curtainOpen);
        this.stage.classList.toggle('no3d', !!s.no3d);
      }
      if (this.curtainsBtn) this.curtainsBtn.setAttribute('aria-label', s.curtainOpen ? 'Close the curtains' : 'Open the curtains and play the showreel');
      if (this.logoEl) this.logoEl.classList.toggle('on', !!s.curtainOpen);
    }

    toggleCurtain() {
      const v = this.vid;
      if (!this.state.curtainOpen) {
        if (v) { v.muted = true; const p = v.play(); if (p && p.catch) p.catch(() => {}); }
        this.target = 1;
        this.setState({ curtainOpen: true });
      } else {
        if (v) v.pause();
        this.target = 0;
        this.setState({ curtainOpen: false });
      }
    }

    bindHero() {
      const btn = this.curtainsBtn;
      if (!btn) return;
      btn.addEventListener('click', () => this.toggleCurtain());
      btn.addEventListener('mousemove', (e) => {
        const r = btn.getBoundingClientRect();
        const x = e.clientX - r.left, y = e.clientY - r.top;
        this.mouse.tx = (x / r.width - 0.5) * 2;
        this.mouse.ty = (y / r.height - 0.5) * 2;
        if (this.hc) {
          this.hc.style.transform = 'translate3d(' + x + 'px,' + y + 'px,0)';
          this.hc.classList.add('on');
        }
        this.warpTitle(e.clientX, e.clientY);
      });
      btn.addEventListener('mouseenter', (e) => {
        this.hover = true;
        if (this.hc) {
          const r = btn.getBoundingClientRect();
          this.hc.style.transition = 'none';
          this.hc.style.transform = 'translate3d(' + (e.clientX - r.left) + 'px,' + (e.clientY - r.top) + 'px,0)';
          void this.hc.offsetWidth;
          this.hc.style.transition = '';
          this.hc.classList.add('on');
        }
      });
      btn.addEventListener('mouseleave', () => {
        this.hover = false; this.mouse.tx = 0; this.mouse.ty = 0;
        if (this.hc) this.hc.classList.remove('on', 'down');
        this.resetTitle();
      });
      btn.addEventListener('mousedown', () => { if (this.hc) this.hc.classList.add('down'); });
      btn.addEventListener('mouseup', () => { if (this.hc) this.hc.classList.remove('down'); });
    }

    // ----------------------------------------------------------------- nav
    scribblePath() {
      const r = (a, b) => a + Math.random() * (b - a);
      const f = (n) => n.toFixed(1);
      const segs = 2 + Math.floor(Math.random() * 3);
      let px = r(-3, 4), py = r(5, 9);
      let d = 'M' + f(px) + ' ' + f(py);
      const slope = r(-2.5, 2.5);
      for (let i = 1; i <= segs; i++) {
        const x = (i * 100) / segs + r(-4, 3);
        const y = 7 + slope * (i / segs) + r(-2.6, 2.6);
        const w = x - px;
        d += ' C' + f(px + w * 0.33 + r(-5, 5)) + ' ' + f(r(1, 13)) + ' ' + f(px + w * 0.66 + r(-5, 5)) + ' ' + f(r(1, 13)) + ' ' + f(x) + ' ' + f(y);
        px = x; py = y;
      }
      const kind = Math.random();
      if (kind < 0.35) {
        d += ' C' + f(r(70, 95)) + ' ' + f(r(8, 13)) + ' ' + f(r(35, 60)) + ' ' + f(r(9, 14)) + ' ' + f(r(4, 30)) + ' ' + f(r(9, 13));
      } else if (kind < 0.55) {
        d += ' q' + f(r(3, 6)) + ' ' + f(r(-6, -3)) + ' ' + f(r(-2, 2)) + ' ' + f(r(-8, -4));
      }
      return d;
    }

    scribble(el) {
      if (!el) return;
      const p = el.querySelector('.scrib path');
      if (!p) return;
      p.setAttribute('d', this.scribblePath());
      el.classList.remove('drawn', 'erase');
      void el.offsetWidth;
      el.classList.add('drawn');
    }

    unscribble(el) {
      if (!el) return;
      el.classList.remove('drawn');
      el.classList.add('erase');
    }

    bindNav() {
      $$('.nl').forEach((a) => {
        a.addEventListener('mouseenter', () => this.scribble(a));
        a.addEventListener('focus', () => this.scribble(a));
        a.addEventListener('mouseleave', () => this.unscribble(a));
        a.addEventListener('blur', () => this.unscribble(a));
      });
    }

    // ------------------------------------------------------------------ 3D
    boot3d() {
      let tries = 0;
      const attempt = () => {
        if (this.dead) return;
        if (window.THREE && this.cv) {
          try { this.init3d(); } catch (e) { if (window.console) console.warn(e); this.setState({ no3d: true }); }
          return;
        }
        tries += 1;
        if (tries > 300) { this.setState({ no3d: true }); return; }
        this.bootT = setTimeout(attempt, 100);
      };
      attempt();
    }

    init3d() {
      const T = window.THREE;
      const cv = this.cv;
      const reduce = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
      const renderer = new T.WebGLRenderer({ canvas: cv, antialias: true, powerPreference: 'high-performance' });
      renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2));
      renderer.outputColorSpace = T.SRGBColorSpace;
      renderer.toneMapping = T.ACESFilmicToneMapping;
      renderer.toneMappingExposure = 1.15;
      renderer.shadowMap.enabled = true;
      renderer.shadowMap.type = T.PCFSoftShadowMap;
      this.renderer = renderer;

      const scene = new T.Scene();
      scene.background = new T.Color(0x050404);
      scene.fog = new T.Fog(0x050404, 30, 56);
      const camera = new T.PerspectiveCamera(42, 1, 0.1, 120);
      const camBase = new T.Vector3(0, 5.0, 24.5);
      const look = new T.Vector3(0, 4.0, 0);
      camera.position.copy(camBase);
      camera.lookAt(look);

      const std = (c, r, extra) => new T.MeshStandardMaterial(Object.assign({ color: c, roughness: r, metalness: 0 }, extra || {}));
      const add = (geo, mat, x, y, z, opts) => {
        const m = new T.Mesh(geo, mat);
        m.position.set(x, y, z);
        if (opts && opts.rx) m.rotation.x = opts.rx;
        if (opts && opts.ry) m.rotation.y = opts.ry;
        if (opts && opts.cast) m.castShadow = true;
        if (opts && opts.receive) m.receiveShadow = true;
        scene.add(m);
        return m;
      };

      // Room shell
      const wallMat = std(0x120d0f, 0.95);
      add(new T.PlaneGeometry(60, 30), std(0x070606, 1), 0, 6, -0.7);
      add(new T.PlaneGeometry(30, 40), std(0x0d090a, 1), 0, -0.85, 18, { rx: -Math.PI / 2, receive: true });
      add(new T.PlaneGeometry(30, 40), std(0x060505, 1), 0, 12.5, 18, { rx: Math.PI / 2 });
      add(new T.PlaneGeometry(40, 16), wallMat, -13.5, 5.5, 18, { ry: Math.PI / 2 });
      add(new T.PlaneGeometry(40, 16), wallMat, 13.5, 5.5, 18, { ry: -Math.PI / 2 });
      const panelGeo = new T.BoxGeometry(0.3, 7.5, 2.4);
      const panelMat = std(0x1c1315, 0.9);
      for (let z = 4; z < 34; z += 3.1) {
        add(panelGeo, panelMat, -13.3, 5.2, z);
        add(panelGeo, panelMat, 13.3, 5.2, z);
      }

      // Stage and proscenium
      const darkWood = std(0x1a110f, 0.55);
      add(new T.BoxGeometry(23, 1.0, 3.2), darkWood, 0, -0.35, 0.5, { receive: true });
      const procMat = std(0x0b0809, 0.9);
      add(new T.BoxGeometry(2.6, 13, 1.4), procMat, -11.5, 5.6, 1.9, { receive: true });
      add(new T.BoxGeometry(2.6, 13, 1.4), procMat, 11.5, 5.6, 1.9, { receive: true });
      add(new T.BoxGeometry(25.6, 2.6, 1.4), procMat, 0, 10.9, 1.9);

      // Screen with the reel
      const screenMat = new T.MeshBasicMaterial({ color: 0x000000, toneMapped: false });
      if (this.vid) {
        const tex = new T.VideoTexture(this.vid);
        tex.colorSpace = T.SRGBColorSpace;
        // "object-fit: cover" for the 15.4 × 6.3 screen: any video ratio is centre-cropped, never stretched
        const fit = () => {
          const v = this.vid, sa = 15.4 / 6.3;
          if (!v.videoWidth || !v.videoHeight) return;
          const va = v.videoWidth / v.videoHeight;
          const rx = va > sa ? sa / va : 1, ry = va > sa ? 1 : va / sa;
          tex.repeat.set(rx, ry);
          tex.offset.set((1 - rx) / 2, (1 - ry) / 2);
        };
        if (this.vid.readyState >= 1) fit();
        this.vid.addEventListener('loadedmetadata', fit);
        screenMat.map = tex;
        screenMat.needsUpdate = true;
      }
      add(new T.PlaneGeometry(15.4, 6.3), screenMat, 0, 4.35, -0.4);

      // Velvet
      const velvet = new T.MeshPhysicalMaterial({
        color: 0x8a0f16, roughness: 0.8, metalness: 0,
        sheen: 1, sheenRoughness: 0.35, sheenColor: new T.Color(0xff5a4f),
        side: T.DoubleSide
      });

      // Curtains: displaced planes, rebuilt every frame
      const makeCurtain = (side, z0) => {
        const sx = 150, sy = 36;
        const geo = new T.PlaneGeometry(1, 1, sx, sy);
        const uv = geo.attributes.uv.array.slice();
        const mesh = new T.Mesh(geo, velvet);
        mesh.castShadow = true;
        mesh.receiveShadow = true;
        mesh.frustumCulled = false;
        scene.add(mesh);
        return { geo: geo, uv: uv, side: side, z0: z0 };
      };
      const curtains = [makeCurtain(-1, 0.78), makeCurtain(1, 0.64)];
      const TAU = Math.PI * 2;
      const W = 9.9, H = 8.75, Y0 = 0.15, NF = 12;
      const updateCurtain = (c, o, t, hv) => {
        const pos = c.geo.attributes.position.array;
        const uv = c.uv;
        const n = uv.length / 2;
        for (let i = 0; i < n; i++) {
          const ux = uv[i * 2], yn = uv[i * 2 + 1];
          const a = c.side < 0 ? 1 - ux : ux;
          let ov = o * 1.25 - 0.25 * (1 - yn);
          ov = ov < 0 ? 0 : ov > 1 ? 1 : ov;
          ov = ov * ov * (3 - 2 * ov);
          const w = W * (1 - 0.84 * ov);
          const xOuter = c.side * 9.6;
          let x = xOuter - c.side * (1 - a) * w;
          const inner = (1 - a) * (1 - a);
          x += c.side * hv * inner * (0.5 + 0.25 * (1 - yn));
          const amp = (0.17 + 0.44 * ov) * (0.86 + 0.14 * Math.sin(a * 31 + yn * 3));
          let z = c.z0 + amp * Math.sin(a * NF * TAU + c.side * 0.7);
          if (!reduce) z += 0.035 * Math.sin(t * 0.9 + a * 7 + yn * 2.2) * (1 - 0.6 * ov);
          const y = Y0 + yn * H + (yn < 0.02 ? 0.06 * Math.sin(a * NF * TAU) : 0);
          pos[i * 3] = x;
          pos[i * 3 + 1] = y;
          pos[i * 3 + 2] = z;
        }
        c.geo.attributes.position.needsUpdate = true;
        c.geo.computeVertexNormals();
      };

      // Valance with scalloped hem
      (() => {
        const geo = new T.PlaneGeometry(1, 1, 260, 10);
        const pos = geo.attributes.position.array;
        const uv = geo.attributes.uv.array;
        for (let i = 0; i < uv.length / 2; i++) {
          const ux = uv[i * 2], yn = uv[i * 2 + 1];
          const low = Math.pow(1 - yn, 3);
          pos[i * 3] = -10.8 + ux * 21.6;
          pos[i * 3 + 1] = 8.15 + yn * 1.5 - low * 0.32 * Math.abs(Math.sin(ux * Math.PI * 15));
          pos[i * 3 + 2] = 1.55 + 0.12 * Math.sin(ux * TAU * 36) + low * 0.06;
        }
        geo.computeVertexNormals();
        const m = new T.Mesh(geo, velvet);
        m.castShadow = true;
        m.receiveShadow = true;
        scene.add(m);
      })();

      // Stepped seating
      const rows = 10, perRow = 21, pitch = 0.9;
      const seatMat = new T.MeshPhysicalMaterial({ color: 0x3d0b10, roughness: 0.88, sheen: 0.7, sheenRoughness: 0.45, sheenColor: new T.Color(0x9a3030) });
      const armMat = std(0x0c0a0a, 0.6);
      const riserMat = std(0x0e0a0b, 1);
      const stepMat = new T.MeshBasicMaterial({ color: 0xffa25a });
      const roundedBox = (w, h, d, r, seg) => {
        const g = new T.BoxGeometry(w, h, d, seg, seg, seg);
        const p = g.attributes.position, nrm = g.attributes.normal;
        const hx = w / 2 - r, hy = h / 2 - r, hz = d / 2 - r;
        const cl = (val, m) => (val < -m ? -m : val > m ? m : val);
        for (let i = 0; i < p.count; i++) {
          const x = p.getX(i), y = p.getY(i), z = p.getZ(i);
          const cx = cl(x, hx), cy = cl(y, hy), cz = cl(z, hz);
          let dx = x - cx, dy = y - cy, dz = z - cz;
          const len = Math.sqrt(dx * dx + dy * dy + dz * dz);
          if (len > 1e-6) {
            dx /= len; dy /= len; dz /= len;
            p.setXYZ(i, cx + dx * r, cy + dy * r, cz + dz * r);
            nrm.setXYZ(i, dx, dy, dz);
          }
        }
        return g;
      };
      const backGeo = roundedBox(0.8, 1.0, 0.24, 0.1, 10);
      const cushGeo = roundedBox(0.76, 0.2, 0.64, 0.08, 10);
      const armGeo = roundedBox(0.1, 0.34, 0.74, 0.045, 6);
      const total = rows * perRow;
      const backs = new T.InstancedMesh(backGeo, seatMat, total);
      const cushs = new T.InstancedMesh(cushGeo, seatMat, total);
      const arms = new T.InstancedMesh(armGeo, armMat, rows * (perRow + 1));
      const dummy = new T.Object3D();
      let k = 0, ka = 0;
      for (let r = 0; r < rows; r++) {
        const z = 6.2 + r * 1.45;
        const fy = -0.85 + r * 0.36;
        if (r > 0) {
          add(new T.BoxGeometry(24, r * 0.36, 1.45), riserMat, 0, -0.85 + r * 0.18, z, { receive: true });
          add(new T.BoxGeometry(0.22, 0.05, 0.05), stepMat, -10.6, fy + 0.03, z - 0.72);
          add(new T.BoxGeometry(0.22, 0.05, 0.05), stepMat, 10.6, fy + 0.03, z - 0.72);
        }
        for (let s = 0; s < perRow; s++) {
          const x = -((perRow - 1) * pitch) / 2 + s * pitch;
          dummy.rotation.set(0.12, 0, 0);
          dummy.position.set(x, fy + 0.92, z + 0.42);
          dummy.updateMatrix();
          backs.setMatrixAt(k, dummy.matrix);
          dummy.rotation.set(0, 0, 0);
          dummy.position.set(x, fy + 0.45, z + 0.02);
          dummy.updateMatrix();
          cushs.setMatrixAt(k, dummy.matrix);
          k += 1;
        }
        for (let s = 0; s <= perRow; s++) {
          const x = -(perRow * pitch) / 2 + s * pitch;
          dummy.rotation.set(0, 0, 0);
          dummy.position.set(x, fy + 0.6, z + 0.05);
          dummy.updateMatrix();
          arms.setMatrixAt(ka, dummy.matrix);
          ka += 1;
        }
      }
      [backs, cushs, arms].forEach((m) => { m.receiveShadow = true; scene.add(m); });

      // Audience silhouettes
      const ink = new T.MeshBasicMaterial({ color: 0x020202 });
      const torsoG = new T.CapsuleGeometry(0.22, 0.5, 6, 14);
      const headG = new T.SphereGeometry(0.135, 18, 14);
      const legG = new T.CapsuleGeometry(0.1, 0.62, 4, 10);
      const armG = new T.CapsuleGeometry(0.065, 0.5, 4, 10);
      const rowZ = (r) => 6.2 + r * 1.45;
      const rowY = (r) => -0.85 + r * 0.36;
      const seatX = (s) => -((perRow - 1) * pitch) / 2 + s * pitch;
      const makePerson = (scl, wide) => {
        const g = new T.Group();
        const body = new T.Group();
        g.add(body);
        const legL = new T.Mesh(legG, ink); legL.position.set(-0.1, 0.42, 0);
        const legR = new T.Mesh(legG, ink); legR.position.set(0.1, 0.42, 0);
        const torso = new T.Mesh(torsoG, ink); torso.position.set(0, 1.18, 0); torso.scale.set(wide, 1, 0.8);
        const head = new T.Mesh(headG, ink); head.position.set(0, 1.79, 0);
        const armPL = new T.Group(); armPL.position.set(-0.27 * wide, 1.5, 0);
        const armPR = new T.Group(); armPR.position.set(0.27 * wide, 1.5, 0);
        const aL = new T.Mesh(armG, ink); aL.position.set(0, -0.3, 0); armPL.add(aL);
        const aR = new T.Mesh(armG, ink); aR.position.set(0, -0.3, 0); armPR.add(aR);
        body.add(legL, legR, torso, head, armPL, armPR);
        g.scale.setScalar(scl);
        scene.add(g);
        return { g: g, body: body, legL: legL, legR: legR, armPL: armPL, armPR: armPR };
      };
      const cast = [
        { row: 9, seat: 3, from: -1, delay: 0.2, scl: 1.0, wide: 1.0 },
        { row: 8, seat: 13, from: 1, delay: 0.6, scl: 0.96, wide: 0.9 },
        { row: 6, seat: 14, from: 1, delay: 1.1, scl: 1.03, wide: 1.05, holder: true },
        { row: 9, seat: 4, from: -1, delay: 1.5, scl: 0.92, wide: 0.88 },
        { row: 7, seat: 15, from: 1, delay: 1.9, scl: 1.05, wide: 1.1 },
        { row: 9, seat: 16, from: 1, delay: 2.5, scl: 0.98, wide: 0.95 },
        { row: 7, seat: 5, from: -1, delay: 2.9, scl: 1.0, wide: 1.0 },
        { row: 8, seat: 11, from: 1, delay: 3.4, scl: 0.9, wide: 0.86 },
        { row: 6, seat: 9, from: -1, delay: 3.8, scl: 1.02, wide: 1.0 }
      ].map((c) => {
        const p = makePerson(c.scl, c.wide);
        const xs = c.from * 11.6, xe = seatX(c.seat);
        return Object.assign(c, p, { xs: xs, xe: xe, walkT: Math.abs(xe - xs) / 2.3 });
      });
      const clamp01 = (x) => (x < 0 ? 0 : x > 1 ? 1 : x);
      const updateCast = (t) => {
        cast.forEach((c) => {
          const z0 = rowZ(c.row), y0 = rowY(c.row);
          const tt = reduce ? 99 : t - c.delay;
          const walkP = clamp01(tt / c.walkT);
          const sitP = clamp01((tt - c.walkT) / 0.8);
          const sitE = sitP * sitP * (3 - 2 * sitP);
          const x = c.xs + (c.xe - c.xs) * (1 - Math.pow(1 - walkP, 1.6));
          const walking = walkP > 0 && walkP < 1;
          const phase = tt * 7.5;
          const bob = walking ? 0.045 * Math.abs(Math.sin(phase)) : 0;
          c.g.position.set(x, y0 + bob - 0.47 * sitE, z0 - 0.62 + 0.66 * sitE);
          c.g.rotation.y = c.from > 0 ? (Math.PI / 2) * (1 - sitE) : (-Math.PI / 2) * (1 - sitE);
          c.g.visible = tt > 0;
          const sw = walking ? Math.sin(phase) * 0.45 : 0;
          c.legL.rotation.x = sw; c.legR.rotation.x = -sw;
          c.armPL.rotation.x = -sw * 0.8; c.armPR.rotation.x = sw * 0.8;
          c.body.rotation.z = walking ? 0.035 * Math.sin(phase) : 0;
        });
      };

      // Light
      scene.add(new T.HemisphereLight(0x3a2a2a, 0x050303, 0.7));
      const spot = new T.SpotLight(0xffd4a8, 1800, 0, 0.42, 0.75, 2);
      spot.position.set(0, 15, 14);
      spot.target.position.set(0, 4.2, 0.7);
      spot.castShadow = true;
      spot.shadow.mapSize.set(2048, 2048);
      spot.shadow.bias = -0.0004;
      spot.shadow.normalBias = 0.03;
      spot.shadow.camera.near = 5;
      spot.shadow.camera.far = 40;
      scene.add(spot, spot.target);
      const rimL = new T.SpotLight(0xffb27a, 300, 0, 0.5, 0.9, 2);
      rimL.position.set(-8, 11, 8);
      rimL.target.position.set(-4, 4, 0.7);
      const rimR = rimL.clone();
      rimR.position.set(8, 11, 8);
      rimR.target = new T.Object3D();
      rimR.target.position.set(4, 4, 0.7);
      scene.add(rimL, rimL.target, rimR, rimR.target);
      const screenLight = new T.SpotLight(0xa9bcff, 0, 0, 1.0, 1, 2);
      screenLight.position.set(0, 4.3, 0.2);
      screenLight.target.position.set(0, 2, 18);
      scene.add(screenLight, screenLight.target);

      // Projector beam: from the logo to the screen
      const corners = [[-7.7, 7.5], [7.7, 7.5], [7.7, 1.2], [-7.7, 1.2]];
      const bPos = [], bApex = [], bW = [];
      const layers = 12;
      for (let li = 0; li < layers; li++) {
        const k = li / (layers - 1);
        const sc = 1.22 - k * 1.06;
        const wgt = 0.35 + 0.65 * k;
        const cs = corners.map((c) => [c[0] * sc, 4.35 + (c[1] - 4.35) * sc]);
        for (let i = 0; i < 4; i++) {
          const a = cs[i], b = cs[(i + 1) % 4];
          bPos.push(0, 0, 0, a[0], a[1], -0.36, b[0], b[1], -0.36);
          bApex.push(1, 0, 0);
          bW.push(wgt, wgt, wgt);
        }
      }
      const beamGeo = new T.BufferGeometry();
      beamGeo.setAttribute('position', new T.Float32BufferAttribute(bPos, 3));
      beamGeo.setAttribute('aApex', new T.Float32BufferAttribute(bApex, 1));
      beamGeo.setAttribute('aW', new T.Float32BufferAttribute(bW, 1));
      const beamMat = new T.ShaderMaterial({
        uniforms: {
          uApex: { value: new T.Vector3(-6, 9, 20) },
          uAxis: { value: new T.Vector3(0, 0, -1) },
          uB: { value: new T.Vector3(1, 0, 0) },
          uN: { value: new T.Vector3(0, 1, 0) },
          uLen: { value: 20 },
          uTime: { value: 0 },
          uOpacity: { value: 0 }
        },
        vertexShader: [
          'attribute float aApex;',
          'attribute float aW;',
          'uniform vec3 uApex;',
          'varying vec3 vW;',
          'varying float vLw;',
          'void main(){',
          '  vLw = aW;',
          '  vec3 p = mix(position, uApex, aApex);',
          '  vec4 w = modelMatrix * vec4(p, 1.0);',
          '  vW = w.xyz;',
          '  gl_Position = projectionMatrix * viewMatrix * w;',
          '}'
        ].join('\n'),
        fragmentShader: [
          'uniform vec3 uApex; uniform vec3 uAxis; uniform vec3 uB; uniform vec3 uN;',
          'uniform float uLen; uniform float uTime; uniform float uOpacity;',
          'varying vec3 vW;',
          'varying float vLw;',
          'void main(){',
          '  vec3 d = vW - uApex;',
          '  float along = dot(d, uAxis);',
          '  float t = clamp(along / uLen, 0.0, 1.0);',
          '  vec3 perp = d - uAxis * along;',
          '  float ang = atan(dot(perp, uB), dot(perp, uN));',
          '  float r1 = sin(ang * 13.0 + uTime * 0.9 + 2.2 * sin(ang * 4.0 - uTime * 0.5));',
          '  float r2 = sin(ang * 29.0 - uTime * 1.3 + 1.5 * sin(t * 6.0 + uTime * 0.7));',
          '  float streak = 0.55 + 0.3 * r1 + 0.15 * r2;',
          '  float drift = 0.8 + 0.2 * sin(t * 18.0 - uTime * 2.4 + ang * 5.0);',
          '  float flick = 0.9 + 0.1 * sin(uTime * 11.3) * sin(uTime * 6.7);',
          '  float fade = (1.0 - 0.8 * pow(t, 0.6)) + 1.4 * exp(-t * 14.0);',
          '  vec3 rd = vW - cameraPosition;',
          '  float s = (-0.4 - cameraPosition.z) / rd.z;',
          '  vec3 hp = cameraPosition + rd * s;',
          '  float inside = min(7.7 - abs(hp.x), min(hp.y - 1.2, 7.5 - hp.y));',
          '  float mask = 1.0 - smoothstep(-0.35, 0.9, inside);',
          '  float a = uOpacity * vLw * fade * max(streak, 0.05) * drift * flick * mask;',
          '  vec3 warm = vec3(1.0, 0.88, 0.7);',
          '  vec3 cool = vec3(0.6, 0.82, 1.0);',
          '  vec3 rose = vec3(1.0, 0.66, 0.86);',
          '  vec3 lime = vec3(0.85, 1.0, 0.62);',
          '  float ph = uTime * 0.45 + ang * 2.5 - t * 3.0;',
          '  vec3 col = warm * (0.5 + 0.5 * sin(ph)) + cool * (0.5 + 0.5 * sin(ph + 2.1)) + rose * (0.5 + 0.5 * sin(ph + 4.2)) * 0.8 + lime * (0.5 + 0.5 * sin(ph * 0.7 + 1.0)) * 0.35;',
          '  col = mix(vec3(1.0, 0.96, 0.9), col / 1.8, 0.75 * smoothstep(0.0, 0.25, t));',
          '  gl_FragColor = vec4(col * a, a);',
          '}'
        ].join('\n'),
        transparent: true,
        depthWrite: false,
        blending: T.AdditiveBlending,
        side: T.DoubleSide,
        toneMapped: false
      });
      const beam = new T.Mesh(beamGeo, beamMat);
      beam.frustumCulled = false;
      beam.renderOrder = 5;
      beam.visible = false;
      // The beam lives on its own blurred canvas layer
      let beamRenderer = null;
      const beamScene = new T.Scene();
      if (this.bcv) {
        try {
          beamRenderer = new T.WebGLRenderer({ canvas: this.bcv, alpha: true, antialias: false, premultipliedAlpha: true });
          beamRenderer.setClearColor(0x000000, 0);
          beamRenderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2) * 0.5);
          this.renderer2 = beamRenderer;
        } catch (e) { beamRenderer = null; }
      }
      if (beamRenderer) beamScene.add(beam); else scene.add(beam);
      const screenCenter = new T.Vector3(0, 4.35, -0.36);
      const tmpV = new T.Vector3();
      const updateBeam = (lit, t) => {
        beam.visible = lit > 0.01;
        if (!beam.visible) return;
        const lg = this.logoEl;
        let nx = -0.85, ny = 0.92;
        if (lg) {
          const lr = lg.getBoundingClientRect(), cr = cv.getBoundingClientRect();
          if (cr.width > 0 && cr.height > 0) {
            nx = ((lr.left + lr.width / 2 - cr.left) / cr.width) * 2 - 1;
            ny = -(((lr.top + lr.height / 2 - cr.top) / cr.height) * 2 - 1);
          }
        }
        camera.updateMatrixWorld();
        tmpV.set(nx, ny, 0.5).unproject(camera).sub(camera.position).normalize();
        const apex = beamMat.uniforms.uApex.value.copy(camera.position).addScaledVector(tmpV, 3.2);
        const axis = beamMat.uniforms.uAxis.value.copy(screenCenter).sub(apex);
        beamMat.uniforms.uLen.value = axis.length();
        axis.normalize();
        const up = Math.abs(axis.y) > 0.9 ? new T.Vector3(1, 0, 0) : new T.Vector3(0, 1, 0);
        beamMat.uniforms.uB.value.crossVectors(axis, up).normalize();
        beamMat.uniforms.uN.value.crossVectors(beamMat.uniforms.uB.value, axis).normalize();
        beamMat.uniforms.uTime.value = t;
        beamMat.uniforms.uOpacity.value = 0.24 * lit;
      };

      // Size
      const resize = () => {
        const host = cv.parentElement;
        if (!host) return;
        const w = host.clientWidth || 1, h = host.clientHeight || 1;
        renderer.setSize(w, h, false);
        if (beamRenderer) beamRenderer.setSize(w, h, false);
        const aspect = w / h;
        const need = 2 * Math.atan((11.2 / 23.8) / aspect) * 180 / Math.PI;
        camera.fov = Math.min(78, Math.max(42, need));
        camera.aspect = aspect;
        camera.updateProjectionMatrix();
      };
      resize();
      if (window.ResizeObserver) {
        this.ro = new ResizeObserver(resize);
        this.ro.observe(cv.parentElement);
      }
      if (window.IntersectionObserver) {
        this.io = new IntersectionObserver((es) => { this.visible = es[0] ? es[0].isIntersecting : true; });
        this.io.observe(cv);
      }

      // Loop
      let last = performance.now();
      const start = last;
      const ease = (x) => (x < 0.5 ? 4 * x * x * x : 1 - Math.pow(-2 * x + 2, 3) / 2);
      const frame = () => {
        if (this.dead) return;
        this.raf = requestAnimationFrame(frame);
        const now = performance.now();
        const dt = Math.min(0.05, (now - last) / 1000);
        last = now;
        if (!this.visible || document.hidden) return;
        const t = (now - start) / 1000;
        const dur = reduce ? 0.35 : 2.6;
        if (this.p < this.target) this.p = Math.min(this.target, this.p + dt / dur);
        else if (this.p > this.target) this.p = Math.max(this.target, this.p - dt / dur);
        const o = ease(this.p);
        const hvTarget = this.hover && this.target === 0 && !reduce ? 1 : 0;
        this.hv += (hvTarget - this.hv) * Math.min(1, dt * 3);
        const m = this.mouse;
        m.x += (m.tx - m.x) * Math.min(1, dt * 2.5);
        m.y += (m.ty - m.y) * Math.min(1, dt * 2.5);
        camera.position.set(camBase.x + m.x * 1.3, camBase.y - m.y * 0.55, camBase.z);
        camera.lookAt(look);
        curtains.forEach((c) => updateCurtain(c, o, t, this.hv));
        const lit = Math.max(0, Math.min(1, (o - 0.12) / 0.6));
        updateBeam(lit, t);
        screenMat.color.setScalar(lit);
        spot.intensity = 1800 * (1 - 0.65 * o);
        rimL.intensity = rimR.intensity = 300 * (1 - 0.5 * o);
        const flick = reduce ? 1 : 1 + 0.18 * Math.sin(t * 7.3) * Math.sin(t * 3.1);
        screenLight.intensity = 1300 * lit * flick;
        updateCast(this.introAt ? (now - this.introAt) / 1000 : -100);
        const v = this.vid;
        if (v && !this.taintChecked && v.readyState >= 2) {
          this.taintChecked = true;
          try {
            const probe = document.createElement('canvas');
            probe.width = probe.height = 2;
            const g = probe.getContext('2d');
            g.drawImage(v, 0, 0, 2, 2);
            g.getImageData(0, 0, 1, 1);
          } catch (err) {
            this.taint = true;
            screenMat.map = null;
            screenMat.needsUpdate = true;
          }
        }
        if (this.taint && v) {
          const corners = [[-7.7, 7.5], [7.7, 7.5], [-7.7, 1.2], [7.7, 1.2]].map((p) => new T.Vector3(p[0], p[1], -0.4).project(camera));
          const W2 = cv.clientWidth, H2 = cv.clientHeight;
          const xs = corners.map((p) => (p.x + 1) / 2 * W2), ys = corners.map((p) => (1 - p.y) / 2 * H2);
          const l = Math.min.apply(null, xs), r = Math.max.apply(null, xs), tp = Math.min.apply(null, ys), b = Math.max.apply(null, ys);
          v.style.transition = 'none';
          v.style.zIndex = '1';
          v.style.inset = 'auto';
          v.style.left = l + 'px';
          v.style.top = tp + 'px';
          v.style.width = (r - l) + 'px';
          v.style.height = (b - tp) + 'px';
          v.style.opacity = String(Math.max(0, (o - 0.55) / 0.45));
        }
        renderer.render(scene, camera);
        if (beamRenderer) beamRenderer.render(beamScene, camera);
        this.firstFrame = true;
      };
      frame();
    }

    // -------------------------------------------------------------- loader
    startLoader() {
      this.loaderEl = ref('loader');
      this.loadPctEl = ref('loadPct');
      this.loadArcEl = ref('loadArc');
      this.loadLineEl = ref('loadLine');
      this.loadPartEls = $$('.ldp');
      const fams = ["400 1em 'Dx Playhigh'", "800 1em 'Archivo'", "400 1em 'Archivo'", "700 1em 'Caveat'"];
      this.fontsTotal = fams.length;
      this.fontsDone = 0;
      const fontDone = () => { this.fontsDone += 1; };
      if (document.fonts && document.fonts.load) {
        fams.forEach((f) => { document.fonts.load(f).then(fontDone, fontDone); });
      } else {
        this.fontsDone = this.fontsTotal;
      }
      const imgs = [this.vid].concat(this.fvs).map((v) => (v ? v.getAttribute('poster') : null)).filter(Boolean);
      this.imgTotal = imgs.length;
      this.imgDone = 0;
      this.imgObjs = imgs.map((src) => {
        const im = new Image();
        im.onload = im.onerror = () => { this.imgDone += 1; };
        im.src = src;
        return im;
      });
      this.loadStart = performance.now();
      this.dispPct = 0;
      this.loadIv = setInterval(() => this.tickLoader(), 80);
    }

    tickLoader() {
      const v = this.vid;
      let vp = 0;
      if (v) {
        if (v.readyState >= 3 || v.error) vp = 1;
        else if (v.duration && v.buffered && v.buffered.length) vp = Math.min(1, v.buffered.end(v.buffered.length - 1) / (v.duration * 0.2));
      }
      const no3d = !!this.state.no3d;
      const parts = [
        { k: 'Fonts', w: 0.15, p: this.fontsTotal ? this.fontsDone / this.fontsTotal : 1 },
        { k: 'Theatre engine', w: 0.2, p: window.THREE || no3d ? 1 : 0 },
        { k: '3D hall', w: 0.15, p: this.firstFrame || no3d ? 1 : 0 },
        { k: 'Showreel', w: 0.35, p: vp },
        { k: 'Posters', w: 0.15, p: this.imgTotal ? this.imgDone / this.imgTotal : 1 }
      ];
      let real = parts.reduce((a, x) => a + x.w * Math.min(1, x.p), 0);
      const elapsed = (performance.now() - this.loadStart) / 1000;
      if (elapsed > 15) real = 1; // safety: never trap the visitor
      const nowT = performance.now(); const dtL = Math.min(0.5, ((nowT - (this.lastTick || nowT)) / 1000)); this.lastTick = nowT; const stepL = Math.max((real - this.dispPct) * (1 - Math.exp(-dtL * 5)), Math.min(real - this.dispPct, dtL * 0.35)); this.dispPct += Math.max(0, stepL);
      if (Math.abs(real - this.dispPct) < 0.004) this.dispPct = real;
      const pct = Math.min(100, Math.floor(this.dispPct * 100 + 0.0001));

      if (this.loadPctEl) this.loadPctEl.textContent = String(pct).padStart(3, '0');
      if (this.loadArcEl) this.loadArcEl.style.strokeDashoffset = String(100 - pct);
      if (this.loaderEl) this.loaderEl.setAttribute('aria-label', 'Loading ' + pct + ' percent');
      if (this.loadLineEl) this.loadLineEl.textContent = pct >= 100 ? 'lights down…' : pct >= 60 ? 'popcorn ready…' : 'finding your seat…';
      this.loadPartEls.forEach((li) => {
        const part = parts.find((x) => x.k === li.getAttribute('data-k'));
        if (!part) return;
        const done = part.p >= 1;
        li.style.color = done ? '#C8FF2E' : '#9C9B95';
        const val = li.querySelector('.ldv');
        if (val) val.textContent = Math.round(Math.min(1, part.p) * 100) + '%';
      });

      if (pct >= 100 && elapsed > 1.0) {
        clearInterval(this.loadIv);
        if (this.loaderEl) this.loaderEl.classList.add('done');
        this.introAt = performance.now() + 1100; // audience starts walking in after the reveal
        setTimeout(() => { if (this.loaderEl) this.loaderEl.classList.add('gone'); }, 1700);
      }
    }

    // ----------------------------------------------------- hero title warp
    warpTitle(cx, cy) {
      const t = this.titleEl;
      if (!t || (this.state && this.state.curtainOpen)) { this.resetTitle(); return; }
      if (window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
      if (!this.titleLetters) this.titleLetters = Array.prototype.slice.call(t.querySelectorAll('.lt'));
      const tr = t.getBoundingClientRect();
      const pad = 140;
      const near = cx > tr.left - pad && cx < tr.right + pad && cy > tr.top - pad && cy < tr.bottom + pad;
      if (!near) { this.resetTitle(); return; }
      t.classList.add('hot');
      this.titleHot = true;
      const R = Math.max(160, tr.height * 0.9);
      this.titleLetters.forEach((el) => {
        // untransformed centre: offset within title + title rect
        let ox = 0, oy = 0, n = el;
        while (n && n !== t) { ox += n.offsetLeft; oy += n.offsetTop; n = n.offsetParent; }
        const lx = tr.left + ox + el.offsetWidth / 2, ly = tr.top + oy + el.offsetHeight / 2;
        const dx = lx - cx, dy = ly - cy;
        const d = Math.sqrt(dx * dx + dy * dy) || 1;
        let f = 1 - d / R;
        if (f <= 0) { el.style.transform = ''; return; }
        f = f * f;
        const push = f * 46;
        const tx = (dx / d) * push, ty = (dy / d) * push * 0.8;
        const rot = (dx / R) * f * 26;
        const sy = 1 + f * 0.42, sx = 1 - f * 0.12;
        el.style.transform = 'translate(' + tx.toFixed(1) + 'px,' + ty.toFixed(1) + 'px) rotate(' + rot.toFixed(1) + 'deg) scale(' + sx.toFixed(3) + ',' + sy.toFixed(3) + ')';
      });
    }

    resetTitle() {
      if (!this.titleHot || !this.titleEl) return;
      this.titleHot = false;
      this.titleEl.classList.remove('hot');
      (this.titleLetters || []).forEach((el) => { el.style.transform = ''; });
    }

    // --------------------------------------------------------------- about
    updateReveal() {
      const root = this.aboutEl;
      if (!root) return;
      const vh = window.innerHeight || 800;
      const reduce = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
      const cl = (x) => (x < 0 ? 0 : x > 1 ? 1 : x);
      let factP = 1;
      root.querySelectorAll('[data-r]').forEach((el) => {
        const r = el.getBoundingClientRect();
        let p;
        if (reduce) p = 1;
        else if (el.getAttribute('data-r') === 'long') p = (vh * 0.92 - r.top) / (r.height + vh * 0.42);
        else p = (vh * 0.96 - r.top) / (vh * 0.5);
        p = cl(p);
        el.style.setProperty('--p', p.toFixed(3));
        if (el.classList.contains('fact') && factP === 1) factP = p;
      });
      if (this.countEl) {
        const n = String(Math.round((Number(this.countEl.getAttribute('data-to')) || 10) * factP));
        if (this.countEl.textContent !== n) this.countEl.textContent = n;
      }
    }

    bindScroll() {
      this.onScroll = () => {
        if (this.scrollRaf) return;
        this.scrollRaf = requestAnimationFrame(() => { this.scrollRaf = 0; this.updateReveal(); });
      };
      window.addEventListener('scroll', this.onScroll, { passive: true });
      document.addEventListener('scroll', this.onScroll, { passive: true, capture: true });
      window.addEventListener('resize', this.onScroll);
      this.updateReveal();
    }

    // --------------------------------------------------------------- films
    renderFilms() {
      const s = this.state;
      const pad = (n) => String(Math.floor(n)).padStart(2, '0');
      $$('li.film').forEach((li) => {
        const i = Number(li.getAttribute('data-film'));
        const secs = Number(li.getAttribute('data-secs')) || 0;
        const isOpen = i === s.openFilm;
        const isPlaying = isOpen && !!s.playing;
        const ft = isOpen ? (secs ? Math.min(s.ft || 0, secs) : s.ft || 0) : 0;
        const row = $('.film-row', li);
        if (row) row.setAttribute('aria-expanded', isOpen ? 'true' : 'false');
        const dot = $('.fdot', li);
        if (dot) dot.style.opacity = isOpen ? '1' : '0';
        const title = $('.ft', li);
        if (title) title.style.color = isOpen ? 'var(--ink)' : 'var(--dim)';
        const acc = $('.acc', li);
        if (acc) acc.classList.toggle('open', isOpen);
        const player = $('.player', li);
        if (player) player.classList.toggle('is-playing', isPlaying);
        const play = $('.fplay', li);
        if (play) play.setAttribute('aria-label', isPlaying ? 'Pause film' : 'Play film');
        const prog = $('.fprog', li);
        if (prog) prog.style.width = (secs ? (ft / secs) * 100 : 0).toFixed(2) + '%';
        const tc = $('.ftc', li);
        if (tc) tc.textContent = pad(ft / 60) + ':' + pad(ft % 60);
      });
    }

    bindFilms() {
      const pauseAll = () => { this.fvs.forEach((v) => { if (v && !v.paused) v.pause(); }); };
      $$('li.film').forEach((li) => {
        const i = Number(li.getAttribute('data-film'));
        const v = $('[data-ref="filmVideo"]', li);
        const togglePlay = () => {
          if (!v) return;
          if (v.paused) {
            const p = v.play();
            if (p && p.catch) p.catch(() => this.setState({ playing: false }));
            this.setState({ openFilm: i, playing: true });
          } else {
            v.pause();
            this.setState({ playing: false });
          }
        };
        const row = $('.film-row', li);
        if (row) row.addEventListener('click', () => {
          const isOpen = this.state.openFilm === i;
          pauseAll();
          this.setState({ openFilm: isOpen ? -1 : i, playing: false, ft: 0 });
        });
        const btn = $('.fplay', li);
        if (btn) btn.addEventListener('click', togglePlay);
        if (v) {
          const setDur = () => {
            if (!isFinite(v.duration) || !v.duration) return;
            li.setAttribute('data-secs', v.duration.toFixed(2));
            const pad = (n) => String(Math.floor(n)).padStart(2, '0');
            $$('.fdur', li).forEach((el) => { el.textContent = pad(v.duration / 60) + ':' + pad(v.duration % 60); });
          };
          if (v.readyState >= 1) setDur();
          v.addEventListener('loadedmetadata', setDur);
          v.addEventListener('click', togglePlay);
          v.addEventListener('timeupdate', () => { if (this.state.openFilm === i) this.setState({ ft: v.currentTime }); });
          v.addEventListener('ended', () => { v.currentTime = 0; this.setState({ playing: false, ft: 0 }); });
        }
      });
    }

    // ---------------------------------------------------------- lazy loops
    bindAutoplay() {
      const vids = $$('video[data-autoplay]');
      if (!vids.length) return;
      if (prefersReduced() || !('IntersectionObserver' in window)) {
        if (!prefersReduced()) vids.forEach((v) => { v.preload = 'auto'; v.play().catch(() => {}); });
        return;
      }
      const io = new IntersectionObserver((entries) => {
        entries.forEach((e) => {
          const v = e.target;
          if (e.isIntersecting) { v.muted = true; v.preload = 'auto'; const p = v.play(); if (p && p.catch) p.catch(() => {}); }
          else if (!v.paused) v.pause();
        });
      }, { rootMargin: '200px 0px' });
      vids.forEach((v) => io.observe(v));
    }

    // ---------------------------------------------------------------- boot
    init() {
      this.bindNav();
      this.bindAutoplay();
      if (!this.stage) return; // project pages: no 3D hero, no loader, no films
      this.bindHero();
      this.bindFilms();
      this.bindScroll();
      this.renderHero();
      this.renderFilms();
      this.startLoader();
      this.boot3d();
    }
  }

  const start = () => { window.site = new Site(); window.site.init(); };
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', start);
  else start();
})();
